#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2017-2018 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://gitlab.com/dominiksalvet/ux430ua-jack-volume
#-------------------------------------------------------------------------------
# PARAMETERS:
#   $1 - build directory path
#   $2 - installation directory path
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# SOFTWARE DEPENDENCIES
#-------------------------------------------------------------------------------

# list of required software
SW_REQUIRED='command echo [ id grep cat chmod sed mkdir cp'

# check if some software is missing
for i in $SW_REQUIRED; do
    # software is missing if at least one piece of software is missing
    if ! command -v "$i" > /dev/null; then
        echo "$0: Required software '$i' is missing, installation canceled." >&2
        exit 1
    fi
done

#-------------------------------------------------------------------------------
# DEFINITIONS
#-------------------------------------------------------------------------------

# sed script - regular expression of line containing a successful exit of a shell script
CONTAINS_EXIT_0='^[[:blank:]]*exit(|[[:blank:]]+0+)([[:blank:]]*|[[:blank:]]+#.*)$'

# configuration files directory
CONFIG_DIR=/etc/ux430ua-jack-volume-config

# normalize the installation directory path represented by '$2' parameter
INSTALL_DIR="$(echo "$2" | sed -E -e 's|/+|/|g; s|/$||')"

# escape delimiters of the installation directory path for later use in a sed script
INSTALL_DIR_ESCAPED="$(echo "$INSTALL_DIR" | sed -E -e 's|/|\\/|g')"

#-------------------------------------------------------------------------------
# CHECK STATE
#-------------------------------------------------------------------------------

# check if arguments passed
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "$0: Please supply non-empty arguments, installation canceled." >&2
    exit 1
fi

# check if already installed
if [ -f "$CONFIG_DIR/install-dir" ]; then
    # get the installation directory
    INSTALLED_DIR="$(cat "$CONFIG_DIR/install-dir")"

    if [ "$INSTALL_DIR" = "$INSTALLED_DIR" ]; then
        echo "The program is already installed in '$INSTALLED_DIR/', installation canceled."
        exit 0
    else
        echo "$0: The program is already installed in '$INSTALLED_DIR/', installation canceled." >&2
        exit 1
    fi
fi

# check if given installation directory path is absolute
if ! echo "$INSTALL_DIR/" | grep -q -E -e '^/'; then
    echo "$0: '$INSTALL_DIR/' isn't an absolute path, installation canceled." >&2
    exit 1
fi

# check if given installation directory exists
if [ ! -d "$INSTALL_DIR/" ]; then
    echo "$0: '$INSTALL_DIR/' doesn't exist, installation canceled." >&2
    exit 1
fi

# check if ux430ua-jack-volume file exists
if [ ! -f "$1/ux430ua-jack-volume" ]; then
    echo "$0: '$1/ux430ua-jack-volume' does not exist, installation canceled." >&2
    exit 1
fi

#-------------------------------------------------------------------------------
# INSTALLATION
#-------------------------------------------------------------------------------

# check if running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "$0: Please run as root, installation canceled." >&2
    exit 1
fi

# create '/etc/rc.local' if it does not exist
if [ ! -f /etc/rc.local ]; then
    echo '#!/bin/sh -e

exit 0' > /etc/rc.local
    echo "'/etc/rc.local' has been created."
# append a successful exit if it does not contain one
elif ! grep -q -E -e "$CONTAINS_EXIT_0" /etc/rc.local; then
    echo 'exit 0' >> /etc/rc.local
    echo "'/etc/rc.local' has been modified to contain a successful exit."
fi

# set the execution permission of '/etc/rc.local'
chmod a+x /etc/rc.local

# create configuration file with the installation directory path
mkdir -p "$CONFIG_DIR/" &&
echo "$INSTALL_DIR" > "$CONFIG_DIR/install-dir" &&
# copy the program
cp "$1/ux430ua-jack-volume" "$INSTALL_DIR/" &&
# add script calling to '/etc/rc.local' file to run the program after boot
sed -i -E -e '/'"$CONTAINS_EXIT_0"'/{s//'"'$INSTALL_DIR_ESCAPED"'\/ux430ua-jack-volume'"'"'\n&/; :add_line; N; badd_line}' /etc/rc.local &&
# create ux430ua-jack-volume-caller for systemd
echo "#!/bin/sh

'$INSTALL_DIR/ux430ua-jack-volume'" > /lib/systemd/system-sleep/ux430ua-jack-volume-caller &&
chmod a+x /lib/systemd/system-sleep/ux430ua-jack-volume-caller || exit 1

# apply the changes immediately (it may not be successful as the program dependencies may be missing)
echo 'Applying changes.'
"$INSTALL_DIR"/ux430ua-jack-volume

# final message
echo 'Installation finished successfully!'
