#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2018 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://gitlab.com/dominiksalvet/ux430ua-jack-volume
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# SOFTWARE DEPENDENCIES
#-------------------------------------------------------------------------------

# list of required software
SW_REQUIRED='command echo [ rm sed grep'

# check if some software is missing
for i in $SW_REQUIRED; do
    # software is missing if at least one piece of software is missing
    if ! command -v "$i" > /dev/null; then
        echo "$0: Required software '$i' is missing, uninstallation canceled." >&2
        exit 1
    fi
done

#-------------------------------------------------------------------------------
# DEFINITIONS
#-------------------------------------------------------------------------------

# configuration files directory
CONFIG_DIR=/etc/ux430ua-jack-volume-config

#-------------------------------------------------------------------------------
# CHECK STATE
#-------------------------------------------------------------------------------

# check if installed
if [ ! -f "$CONFIG_DIR/install-dir" ]; then
    echo "The uninstaller can't detect the program on this system, uninstallation canceled."
    exit 0
fi

# get the installation directory
INSTALLED_DIR="$(cat "$CONFIG_DIR/install-dir")"
echo "The detected installation directory path is '$INSTALLED_DIR/'."

# escape delimiters of the installation directory for later use in a sed script
INSTALLED_DIR_ESCAPED="$(echo "$INSTALLED_DIR" | sed -E -e 's|/|\\/|g')"

#-------------------------------------------------------------------------------
# UNINSTALLATION
#-------------------------------------------------------------------------------

# check if running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "$0: Please run as root, uninstallation canceled." >&2
    exit 1
fi

# remove the program
rm /lib/systemd/system-sleep/ux430ua-jack-volume-caller
sed -i -E -e '/^[[:blank:]]*'"'$INSTALLED_DIR_ESCAPED\/ux430ua-jack-volume'"'(| .*)$/d' /etc/rc.local
rm "$INSTALLED_DIR/ux430ua-jack-volume"
rm "$CONFIG_DIR/install-dir"

# final message
echo 'Uninstallation finished successfully! In order to apply the changes, reboot your device.'
