#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2018 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://gitlab.com/dominiksalvet/ux430ua-jack-volume
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# SOFTWARE DEPENDENCIES
#-------------------------------------------------------------------------------

# list of required software
SW_REQUIRED='command echo [ rm sed'

# check if some software is missing
for i in $SW_REQUIRED; do
    # software is missing if at least one piece of software is missing
    if ! command -v "$i" > /dev/null; then
        echo "$0: Required software '$i' is missing." >&2
        exit 1
    fi
done

#-------------------------------------------------------------------------------
# DEFINITIONS
#-------------------------------------------------------------------------------

# installation directory of this program
INSTALL_DIR=/usr/local/bin

#-------------------------------------------------------------------------------
# CHECK STATE
#-------------------------------------------------------------------------------

# check if already uninstalled
if [ ! -f "$INSTALL_DIR/ux430ua-jack-volume" ]; then
    echo 'The program is not installed.'
    exit 0
fi

#-------------------------------------------------------------------------------
# UNINSTALLATION
#-------------------------------------------------------------------------------

# check if running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "$0: Please run as root." >&2
    exit 1
fi

# remove program's caller from systemd
rm /lib/systemd/system-sleep/ux430ua-jack-volume-caller
# remove all lines calling the program from '/etc/rc.local'
sed -i -E -e '/^[[:blank:]]*'"'.*\/ux430ua-jack-volume'"'(| .*)$/d' /etc/rc.local
sed -i -E -e '/^[[:blank:]]*([^[:blank:]]|\\ |\\	)*\/ux430ua-jack-volume(| .*)$/d' /etc/rc.local
# remove the program itself
rm "$INSTALL_DIR/ux430ua-jack-volume"
