#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# https://github.com/dominiksalvet/ux430ua-jack-volume
#-------------------------------------------------------------------------------

ux430ua-jack-volume
