#!/bin/bash

#-------------------------------------------------------------------------------
# Copyright 2018-2019 Dominik Salvet
# https://github.com/dominiksalvet/ux430ua-jack-volume
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# APPLY TAB COMPLETION
#-------------------------------------------------------------------------------

# DESCRIPTION:
#   Prepare a hint consisting of words that can be used from the current part of
#   word.
_ux430ua-jack-volume() {
    local WORDS='-help -about -version' &&

    # generate hint from available ux430ua-jack-volume's action
    mapfile -t COMPREPLY < <(compgen -W "$WORDS" -- "${COMP_WORDS[COMP_CWORD]}")
}

# assign a function to be called when TAB complete is required when ux430ua-jack-volume is used
complete -F _ux430ua-jack-volume ux430ua-jack-volume
