#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2017-2020 Dominik Salvet
# https://github.com/dominiksalvet/ux430ua-jack-volume
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# SOFTWARE DEPENDENCIES
#-------------------------------------------------------------------------------

# list of required software
SW_REQUIRED='command echo [ id hda-verb'

# check if some software is missing
for sw in $SW_REQUIRED; do
    # software is missing if at least one piece of software is missing
    if ! command -v "$sw" > /dev/null; then
        echo "$0: Required software $sw is missing." >&2; exit 1
    fi
done

#-------------------------------------------------------------------------------
# DEFINITIONS
#-------------------------------------------------------------------------------

# the current version of the program
VERSION=2.5.0

HELP_MESSAGE="USAGE: $0 [OPTION]...

OPTION:
  -help     show this help and exit
  -about    show information and exit
  -version  show version and exit"

ABOUT_MESSAGE="ux430ua-jack-volume $VERSION
Fix low volume of ASUS ZenBook UX430UA running Linux.

Copyright 2017-2020 Dominik Salvet
https://github.com/dominiksalvet/ux430ua-jack-volume"

#-------------------------------------------------------------------------------
# PROCESSING PARAMETERS
#-------------------------------------------------------------------------------

# processing each parameter separately
for opt in "$@"; do
    case "$opt" in
        -help) echo "$HELP_MESSAGE"; exit ;;
        -about) echo "$ABOUT_MESSAGE"; exit ;;
        -version) echo "$VERSION"; exit ;;
        *) echo "$0: The option '$opt' was not recognized." >&2; exit 1 ;;
    esac
done

#-------------------------------------------------------------------------------
# APPLY CONFIGURATION
#-------------------------------------------------------------------------------

# check if character device file for sound driving exists
if [ ! -c /dev/snd/hwC0D0 ]; then
    echo "$0: Character device '/dev/snd/hwC0D0' does not exist." >&2; exit 1
fi

# check if running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "$0: Please run as root." >&2; exit 1
fi

# set up output audio jack volume level
hda-verb /dev/snd/hwC0D0 0x20 SET_COEF_INDEX 0x67 > /dev/null 2>&1 &&
hda-verb /dev/snd/hwC0D0 0x20 SET_PROC_COEF 0x3000 > /dev/null 2>&1
