#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://github.com/dominiksalvet/ux430ua-jack-volume
#-------------------------------------------------------------------------------


ux430ua-jack-volume
