#-------------------------------------------------------------------------------
# Copyright 2019-2020 Dominik Salvet
# https://github.com/dominiksalvet/ux430ua-jack-volume
#-------------------------------------------------------------------------------

name: CI
on: [push, pull_request]

jobs:
  Analysis:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Check shellcheck
      run: shellcheck --version

    - name: Check source files
      run: shellcheck src/ux430ua-jack-volume

    - name: Check install files
      run: |
        shellcheck .install/install-global-Linux
        shellcheck .install/uninstall-global-Linux
