name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Analysis
      run: |
        shellcheck --version
        shellcheck src/*
        shellcheck .gitpack/install/global/postcp .gitpack/install/global/precp .gitpack/install/global/prerm
