name: CI
on: push

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Check shellcheck
      run: shellcheck --version

    - name: Check source
      run: shellcheck src/*
      
